import { Dimensions, StyleSheet } from "react-native";

export default StyleSheet.create({
  icon: {
    position: "absolute",
    height: Dimensions.get("window").width,
    width: Dimensions.get("window").width,
    zIndex: 0,
  },
  title: {
    fontSize: 22,
    color: "rgb(105, 64, 255)",
    zIndex: 0,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  price: {
    fontSize: 25,
    fontWeight: "bold",
    color: "rgb(105, 64, 255)",
    zIndex: 0,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  categoryLabel: {
    fontSize: 14,
    color: "rgba(105, 64, 255, 0.72)",
    zIndex: 0,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  category: {
    fontSize: 17,
    color: "rgb(105, 64, 255)",
    zIndex: 0,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  categoryIcon: {
    height: 22,
    width: 22,
    tintColor: "rgb(105, 64, 255)",
  },
  info: {
    zIndex: 1,
    width: Dimensions.get("window").width,
    marginTop: Dimensions.get("window").width - 12.5,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    backgroundColor: "white",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  infoLeft: {
    padding: 20,
    width: "60%",
    height: "100%",
    flexDirection: "column",
    gap: 5,
  },
  infoRight: {
    padding: 20,
    width: "40%",
    height: "100%",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 5,
  },
  button: {
    height: 50,
    width: Dimensions.get("window").width / 3 - 10,
    marginRight: 10,
    textAlign: "center",
    textAlignVertical: "center",
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
    backgroundColor: "rgb(105, 64, 255)",
    borderRadius: 10,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonIcon: {
    height: 30,
    width: 30,
    tintColor: "white",
  },
  topNavBar: {
    zIndex: 1,
    height: 60,
    width: Dimensions.get("window").width,
    paddingTop: 10,
    marginTop: 20,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    position: "absolute",
  },
  topNavBarIcon: {
    tintColor: "white",
    height: 30,
    width: 30,
    marginHorizontal: 20,
  },
  descriptionBackground: {
    backgroundColor: "white",
    width: Dimensions.get("window").width,
  },
  description: {
    padding: 20,
    margin: 10,
    paddingTop: 10,
    paddingBottom: 10,
  },
  descriptionText: {
    color: "#333333",
    fontWeight: "bold",
    paddingLeft: 10,
    paddingRight: 10,
    lineHeight: 24,
    fontSize: 18,
  },
});
